"""Genera ADN simbólico base de los 22 Arcanos Mayores (Rider-Waite-Smith)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "cards"

# id, nombre, original, numero, legacy_file, elementos, simbolos, personajes, dirs,
# keywords(n,luz,sombra), arquetipos, emociones, etapas, fuentes

MAJOR = [
    {
        "id": "major_00_fool",
        "nombre": "El Loco",
        "nombre_original": "The Fool",
        "numero": 0,
        "legacy_filename": "el_loco.png",
        "elementos": ["aire"],
        "simbolos": ["caminante", "perro", "precipicio", "rosa", "saco", "sol"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "avance"}],
        "direcciones": {"mirada": ["adelante"], "movimiento": ["ascendente"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["inicio", "potencial", "viaje"],
            "luz": ["inocencia", "apertura", "confianza"],
            "sombra": ["imprudencia", "ingenuidad", "caos"],
        },
        "arquetipos": ["inocencia", "viaje_heroe", "exploracion"],
        "emociones": ["curiosidad", "entusiasmo", "vulnerabilidad"],
        "etapas_narrativas": ["inicio", "llamada"],
    },
    {
        "id": "major_01_magician",
        "nombre": "El Mago",
        "nombre_original": "The Magician",
        "numero": 1,
        "legacy_filename": "el_mago.png",
        "elementos": ["aire", "fuego"],
        "simbolos": ["mesa", "copa", "espada", "baston", "moneda", "infinito", "serpiente"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "invocacion"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["vertical"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["voluntad", "habilidad", "recursos"],
            "luz": ["manifestacion", "enfoque", "creacion"],
            "sombra": ["manipulacion", "engaño", "dispersión"],
        },
        "arquetipos": ["magia_voluntad", "manifestacion", "poder_personal"],
        "emociones": ["determinacion", "confianza", "orgullo"],
        "etapas_narrativas": ["inicio", "desarrollo"],
    },
    {
        "id": "major_02_high_priestess",
        "nombre": "La Sacerdotisa",
        "nombre_original": "The High Priestess",
        "numero": 2,
        "legacy_filename": "la_sacerdotisa.png",
        "elementos": ["agua"],
        "simbolos": ["columnas", "velo", "luna", "libro", "cruz", "granada"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "estatico"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["misterio", "intuicion", "umbral"],
            "luz": ["sabiduria", "escucha", "claridad interior"],
            "sombra": ["secreto", "pasividad", "ocultamiento"],
        },
        "arquetipos": ["misterio", "maestro_interior", "busqueda_interior"],
        "emociones": ["calma", "intuicion", "serenidad"],
        "etapas_narrativas": ["umbrales", "revelacion"],
    },
    {
        "id": "major_03_empress",
        "nombre": "La Emperatriz",
        "nombre_original": "The Empress",
        "numero": 3,
        "legacy_filename": "la_emperatriz.png",
        "elementos": ["tierra"],
        "simbolos": ["trono", "trigo", "jardin", "venus", "corona", "rio"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "reposo"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["abundancia", "naturaleza", "cuerpo"],
            "luz": ["cuidado", "creatividad", "fertilidad"],
            "sombra": ["exceso", "dependencia", "estancamiento"],
        },
        "arquetipos": ["fertilidad", "cuidado", "creacion"],
        "emociones": ["ternura", "plenitud", "amor"],
        "etapas_narrativas": ["desarrollo", "integracion"],
    },
    {
        "id": "major_04_emperor",
        "nombre": "El Emperador",
        "nombre_original": "The Emperor",
        "numero": 4,
        "legacy_filename": "el_emperador.png",
        "elementos": ["fuego"],
        "simbolos": ["trono", "armadura", "montana", "cetro", "carneros"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "autoridad"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["estructura", "orden", "limites"],
            "luz": ["estabilidad", "proteccion", "liderazgo"],
            "sombra": ["rigidez", "control", "dominio"],
        },
        "arquetipos": ["estructura_autoridad", "disciplina", "limite"],
        "emociones": ["determinacion", "orgullo", "seguridad"],
        "etapas_narrativas": ["desarrollo", "estructura"],
    },
    {
        "id": "major_05_hierophant",
        "nombre": "El Hierofante",
        "nombre_original": "The Hierophant",
        "numero": 5,
        "legacy_filename": "el_hierofante.png",
        "elementos": ["tierra"],
        "simbolos": ["pilares", "llave", "bendicion", "trono", "acólitos", "cruz"],
        "personajes": [
            {"tipo": "figura_humana", "cantidad": 1, "movimiento": "enseñanza"},
            {"tipo": "figura_humana", "cantidad": 2, "movimiento": "escucha"},
        ],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["tradicion", "enseñanza", "rito"],
            "luz": ["guia", "pertenencia", "conocimiento"],
            "sombra": ["dogma", "conformismo", "jerarquia"],
        },
        "arquetipos": ["maestro_interior", "orden_natural", "vocacion"],
        "emociones": ["reverencia", "confianza", "duda"],
        "etapas_narrativas": ["desarrollo", "prueba"],
    },
    {
        "id": "major_06_lovers",
        "nombre": "Los Enamorados",
        "nombre_original": "The Lovers",
        "numero": 6,
        "legacy_filename": "los_enamorados.png",
        "elementos": ["aire"],
        "simbolos": ["angel", "arbol", "serpiente", "nube", "sol", "pareja"],
        "personajes": [
            {"tipo": "figura_angelica", "cantidad": 1, "movimiento": "bendicion"},
            {"tipo": "pareja", "cantidad": 2, "movimiento": "eleccion"},
        ],
        "direcciones": {"mirada": ["arriba", "frente"], "movimiento": ["vertical"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["relacion", "eleccion", "valores"],
            "luz": ["union", "armonia", "compromiso"],
            "sombra": ["tentacion", "indecision", "division"],
        },
        "arquetipos": ["amor_eleccion", "union", "conexion"],
        "emociones": ["amor", "deseo", "vulnerabilidad"],
        "etapas_narrativas": ["llamada", "desarrollo"],
    },
    {
        "id": "major_07_chariot",
        "nombre": "El Carro",
        "nombre_original": "The Chariot",
        "numero": 7,
        "legacy_filename": "el_carro.png",
        "elementos": ["agua"],
        "simbolos": ["carro", "esfinge", "armadura", "ciudad", "luna", "estrella"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "avance"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["adelante"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["direccion", "movimiento", "voluntad"],
            "luz": ["victoria", "disciplina", "foco"],
            "sombra": ["agresion", "imposicion", "impulso ciego"],
        },
        "arquetipos": ["poder_personal", "viaje_heroe", "disciplina"],
        "emociones": ["coraje", "determinacion", "orgullo"],
        "etapas_narrativas": ["desarrollo", "prueba"],
    },
    {
        "id": "major_08_strength",
        "nombre": "La Fuerza",
        "nombre_original": "Strength",
        "numero": 8,
        "legacy_filename": "la_fuerza.png",
        "elementos": ["fuego"],
        "simbolos": ["leon", "infinito", "flores", "mujer", "montana"],
        "personajes": [
            {"tipo": "figura_humana", "cantidad": 1, "movimiento": "apaciguar"},
            {"tipo": "animal", "cantidad": 1, "movimiento": "contencion"},
        ],
        "direcciones": {"mirada": ["abajo"], "movimiento": ["estatico"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["dominio interior", "instinto", "coraje"],
            "luz": ["compasión", "paciencia", "integracion"],
            "sombra": ["represion", "violencia", "orgullo"],
        },
        "arquetipos": ["fuerza_serena", "integracion", "contraste_luz_sombra"],
        "emociones": ["calma", "coraje", "ternura"],
        "etapas_narrativas": ["prueba", "integracion"],
    },
    {
        "id": "major_09_hermit",
        "nombre": "El Ermitaño",
        "nombre_original": "The Hermit",
        "numero": 9,
        "legacy_filename": "el_ermitanio.png",
        "elementos": ["tierra"],
        "simbolos": ["linterna", "baston", "montana", "capa", "nieve"],
        "personajes": [{"tipo": "anciano", "cantidad": 1, "movimiento": "ascenso"}],
        "direcciones": {"mirada": ["abajo"], "movimiento": ["ascendente"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["soledad", "busqueda", "guia"],
            "luz": ["sabiduria", "introspeccion", "claridad"],
            "sombra": ["aislamiento", "retiro excesivo", "frialdad"],
        },
        "arquetipos": ["busqueda_interior", "sabiduria", "maestro_interior"],
        "emociones": ["soledad", "serenidad", "humildad"],
        "etapas_narrativas": ["umbrales", "revelacion"],
    },
    {
        "id": "major_10_wheel_of_fortune",
        "nombre": "La Rueda de la Fortuna",
        "nombre_original": "Wheel of Fortune",
        "numero": 10,
        "legacy_filename": "la_rueda_de_la_fortuna.png",
        "elementos": ["fuego"],
        "simbolos": ["rueda", "esfinge", "serpiente", "nube", "letras", "criatura"],
        "personajes": [{"tipo": "criatura_mitica", "cantidad": 4, "movimiento": "circular"}],
        "direcciones": {"mirada": [], "movimiento": ["circular"], "orientacion_general": "circular"},
        "palabras_clave": {
            "neutrales": ["ciclo", "cambio", "destino aparente"],
            "luz": ["oportunidad", "giro favorable", "expansion"],
            "sombra": ["inestabilidad", "fatalismo", "perdida de control"],
        },
        "arquetipos": ["cambio_ciclo", "fortuna", "transito"],
        "emociones": ["asombro", "ansiedad", "esperanza"],
        "etapas_narrativas": ["cambio", "transito"],
    },
    {
        "id": "major_11_justice",
        "nombre": "La Justicia",
        "nombre_original": "Justice",
        "numero": 11,
        "legacy_filename": "la_justicia.png",
        "elementos": ["aire"],
        "simbolos": ["balanza", "espada", "trono", "corona", "velo"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "equilibrio"}],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["equilibrio", "verdad", "consecuencia"],
            "luz": ["claridad", "responsabilidad", "equidad"],
            "sombra": ["juicio severo", "rigidez", "culpa"],
        },
        "arquetipos": ["juicio_moral", "equilibrio", "limite"],
        "emociones": ["claridad", "seriedad", "calma"],
        "etapas_narrativas": ["revelacion", "prueba"],
    },
    {
        "id": "major_12_hanged_man",
        "nombre": "El Colgado",
        "nombre_original": "The Hanged Man",
        "numero": 12,
        "legacy_filename": "el_colgado.png",
        "elementos": ["agua"],
        "simbolos": ["arbol", "halo", "cuerda", "inversion", "pierna cruzada"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "suspension"}],
        "direcciones": {"mirada": ["abajo"], "movimiento": ["descendente"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["pausa", "perspectiva", "entrega"],
            "luz": ["insight", "aceptacion", "sacrificio consciente"],
            "sombra": ["estancamiento", "victimismo", "inaccion"],
        },
        "arquetipos": ["sacrificio", "pasaje", "busqueda_interior"],
        "emociones": ["calma", "rendicion", "asombro"],
        "etapas_narrativas": ["umbrales", "transformacion"],
    },
    {
        "id": "major_13_death",
        "nombre": "La Muerte",
        "nombre_original": "Death",
        "numero": 13,
        "legacy_filename": "la_muerte.png",
        "elementos": ["agua"],
        "simbolos": ["esqueleto", "caballo", "bandera", "sol", "rio", "torre"],
        "personajes": [
            {"tipo": "figura_humana", "cantidad": 1, "movimiento": "avance"},
            {"tipo": "figura_humana", "cantidad": 3, "movimiento": "reaccion"},
        ],
        "direcciones": {"mirada": ["adelante"], "movimiento": ["adelante"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["final", "transicion", "corte"],
            "luz": ["renacimiento", "liberacion", "renovacion"],
            "sombra": ["miedo", "resistencia", "pérdida"],
        },
        "arquetipos": ["muerte_renacimiento", "transformacion", "pasaje"],
        "emociones": ["miedo", "alivio", "tristeza"],
        "etapas_narrativas": ["ruptura", "transformacion", "renacimiento"],
    },
    {
        "id": "major_14_temperance",
        "nombre": "La Templanza",
        "nombre_original": "Temperance",
        "numero": 14,
        "legacy_filename": "la_templanza.png",
        "elementos": ["fuego", "agua"],
        "simbolos": ["angel", "copa_doble", "agua", "camino", "iris", "sol"],
        "personajes": [{"tipo": "figura_angelica", "cantidad": 1, "movimiento": "vertido"}],
        "direcciones": {"mirada": ["abajo"], "movimiento": ["circular"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["mezcla", "moderacion", "flujo"],
            "luz": ["equilibrio", "sanacion", "paciencia"],
            "sombra": ["indecision", "dilucion", "evitacion"],
        },
        "arquetipos": ["templanza_alquimia", "equilibrio", "integracion"],
        "emociones": ["calma", "paz", "esperanza"],
        "etapas_narrativas": ["integracion", "desarrollo"],
    },
    {
        "id": "major_15_devil",
        "nombre": "El Diablo",
        "nombre_original": "The Devil",
        "numero": 15,
        "legacy_filename": "el_diablo.png",
        "elementos": ["tierra"],
        "simbolos": ["cadenas", "antorcha", "cuernos", "invertido", "pareja", "pedestal"],
        "personajes": [
            {"tipo": "figura_diabolica", "cantidad": 1, "movimiento": "dominio"},
            {"tipo": "pareja", "cantidad": 2, "movimiento": "atadura"},
        ],
        "direcciones": {"mirada": ["frente"], "movimiento": ["estatico"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["atadura", "deseo", "sombra"],
            "luz": ["conciencia", "humor", "liberacion posible"],
            "sombra": ["adiccion", "manipulacion", "materialismo"],
        },
        "arquetipos": ["sombra", "contraste_luz_sombra", "rebeldia"],
        "emociones": ["deseo", "miedo", "fascinacion"],
        "etapas_narrativas": ["conflicto", "crisis"],
    },
    {
        "id": "major_16_tower",
        "nombre": "La Torre",
        "nombre_original": "The Tower",
        "numero": 16,
        "legacy_filename": "la_torre.png",
        "elementos": ["fuego"],
        "simbolos": ["torre", "rayo", "corona", "fuego", "caida", "nubes"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 2, "movimiento": "caida"}],
        "direcciones": {"mirada": [], "movimiento": ["descendente"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["ruptura", "revelacion", "cambio abrupto"],
            "luz": ["liberacion", "verdad", "despertar"],
            "sombra": ["destruccion", "resistencia", "caos"],
        },
        "arquetipos": ["derrumbe_de_estructuras", "liberacion_forzada", "crisis"],
        "emociones": ["miedo", "shock", "alivio"],
        "etapas_narrativas": ["crisis", "ruptura", "transformacion"],
    },
    {
        "id": "major_17_star",
        "nombre": "La Estrella",
        "nombre_original": "The Star",
        "numero": 17,
        "legacy_filename": "la_estrella.png",
        "elementos": ["aire"],
        "simbolos": ["estrella", "agua", "jarra", "ave", "desnudez", "montana"],
        "personajes": [{"tipo": "figura_humana", "cantidad": 1, "movimiento": "vertido"}],
        "direcciones": {"mirada": ["agua"], "movimiento": ["flujo"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["esperanza", "inspiracion", "quietud"],
            "luz": ["sanacion", "confianza", "guia"],
            "sombra": ["idealizacion", "desconexion", "espera pasiva"],
        },
        "arquetipos": ["renovacion", "esperanza", "integracion"],
        "emociones": ["esperanza", "paz", "serenidad"],
        "etapas_narrativas": ["integracion", "renacimiento"],
    },
    {
        "id": "major_18_moon",
        "nombre": "La Luna",
        "nombre_original": "The Moon",
        "numero": 18,
        "legacy_filename": "la_luna.png",
        "elementos": ["agua"],
        "simbolos": ["luna", "perro", "lobo", "cangrejo", "camino", "torres"],
        "personajes": [{"tipo": "animal", "cantidad": 3, "movimiento": "aullido"}],
        "direcciones": {"mirada": ["luna"], "movimiento": ["adelante"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["inconsciente", "ilusion", "ciclo"],
            "luz": ["intuicion", "imaginacion", "viaje nocturno"],
            "sombra": ["confusion", "miedo", "engaño"],
        },
        "arquetipos": ["misterio", "sombra", "busqueda_interior"],
        "emociones": ["miedo", "ansiedad", "fascinacion"],
        "etapas_narrativas": ["umbrales", "prueba"],
    },
    {
        "id": "major_19_sun",
        "nombre": "El Sol",
        "nombre_original": "The Sun",
        "numero": 19,
        "legacy_filename": "el_sol.png",
        "elementos": ["fuego"],
        "simbolos": ["sol", "ninio", "caballo", "girasoles", "muro"],
        "personajes": [
            {"tipo": "ninio", "cantidad": 1, "movimiento": "alegria"},
            {"tipo": "animal", "cantidad": 1, "movimiento": "avance"},
        ],
        "direcciones": {"mirada": ["frente"], "movimiento": ["adelante"], "orientacion_general": "horizontal"},
        "palabras_clave": {
            "neutrales": ["claridad", "vitalidad", "exito"],
            "luz": ["alegria", "verdad", "generosidad"],
            "sombra": ["egocentrismo", "exceso", "ceguera solar"],
        },
        "arquetipos": ["revelacion", "renovacion", "integracion"],
        "emociones": ["alegria", "euforia", "confianza"],
        "etapas_narrativas": ["resolucion", "integracion"],
    },
    {
        "id": "major_20_judgement",
        "nombre": "El Juicio",
        "nombre_original": "Judgement",
        "numero": 20,
        "legacy_filename": "el_juicio.png",
        "elementos": ["fuego", "agua"],
        "simbolos": ["trompeta", "angel", "tumbas", "cruz", "montañas", "mar"],
        "personajes": [
            {"tipo": "figura_angelica", "cantidad": 1, "movimiento": "llamada"},
            {"tipo": "figura_humana", "cantidad": 3, "movimiento": "despertar"},
        ],
        "direcciones": {"mirada": ["arriba"], "movimiento": ["ascendente"], "orientacion_general": "vertical"},
        "palabras_clave": {
            "neutrales": ["llamada", "evaluacion", "despertar"],
            "luz": ["renacimiento", "perdon", "proposito"],
            "sombra": ["autocritica", "juicio severo", "culpa"],
        },
        "arquetipos": ["juicio_llamada", "renacimiento", "revelacion"],
        "emociones": ["asombro", "alivio", "esperanza"],
        "etapas_narrativas": ["revelacion", "renacimiento", "cierre"],
    },
    {
        "id": "major_21_world",
        "nombre": "El Mundo",
        "nombre_original": "The World",
        "numero": 21,
        "legacy_filename": "el_mundo.png",
        "elementos": ["tierra", "espiritu"],
        "simbolos": ["guirnalda", "danza", "tetramorfos", "cintas", "cielo"],
        "personajes": [
            {"tipo": "figura_humana", "cantidad": 1, "movimiento": "danza"},
            {"tipo": "criatura_mitica", "cantidad": 4, "movimiento": "vigilancia"},
        ],
        "direcciones": {"mirada": ["frente"], "movimiento": ["circular"], "orientacion_general": "circular"},
        "palabras_clave": {
            "neutrales": ["completitud", "ciclo", "integracion"],
            "luz": ["logro", "plenitud", "sintesis"],
            "sombra": ["cierre prematuro", "inercia", "autocomplacencia"],
        },
        "arquetipos": ["mundo_completitud", "integracion", "viaje_heroe"],
        "emociones": ["plenitud", "alegria", "paz"],
        "etapas_narrativas": ["integracion", "cierre", "resolucion"],
    },
]


def digital_root(n: int) -> int:
    if n == 0:
        return 0
    while n > 9:
        n = sum(int(d) for d in str(n))
    return n


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for item in MAJOR:
        card = {
            **item,
            "tipo": "arcano_mayor",
            "palo": None,
            "mazo": "rider_waite_smith",
            "imagen": f"cartas/{item['legacy_filename']}",
            "colores": {
                "dominantes_rgb": [],
                "dominantes_hex": [],
                "dominantes_lab": [],
                "porcentajes": [],
                "luminosidad_media": 0.0,
                "saturacion_media": 0.0,
                "temperatura_visual": "desconocida",
                "histograma_hue_bins": [],
            },
            "numerologia": {"numero": item["numero"], "reduccion": digital_root(item["numero"])},
            "fuentes": ["tradicion_rws_comparada", "anotacion_laboratorio_v1"],
            "version": 1,
            "attributions": {},
        }
        path = OUT / f"{item['id']}.json"
        path.write_text(json.dumps(card, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"wrote {path.name}")


if __name__ == "__main__":
    main()
